-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTqYN3dBUfqDAroK4Es8OOw2H0KFbKjY2xuMOLCvmllSgCgYIKoZIzj0DAQehRANCAASWinWY00VRBq/0oSfbZnSEn4T+ueJF5W6D/+aByiQfQWHYlQNtnD6fZgolc1u35+cW7nrUuxiYBzibO4majah6
-----END PRIVATE KEY-----