# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'WeexDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeexDemo

	pod ‘WeexSDK‘
	pod ‘SocketRocket‘
	pod ‘WXDevtool‘,:configuration => [‘Debug‘]


  target 'WeexDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeexDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
